Edge to edge in main branch
google-developer-training/basic-android-kotlin-compose-training-inventory-app pull request #57
Opened 2023-08-24 21:58 UTC by android-dev-lxl

2024-02-02 19:09 UTC, johnshea requested changes

2024-02-02 19:09 UTC, johnshea commented on app/src/main/java/com/example/inventory/ui/item/ItemEntryScreen.kt
>  import androidx.compose.material3.TextFieldDefaults
remove unused import

2024-02-02 19:09 UTC, johnshea commented on app/src/main/java/com/example/inventory/ui/item/ItemEntryScreen.kt
ln 187 - arguments should be on their own lines

2024-02-02 19:09 UTC, johnshea commented on app/src/main/java/com/example/inventory/ui/home/HomeScreen.kt
ln 201 - fix identing

2024-02-14 20:36 UTC, android-dev-lxl commented on app/src/main/java/com/example/inventory/ui/theme/Theme.kt
>      val view = LocalView.current
Added to main branch

2024-04-09 14:31 UTC, johnshea approved these changes

2024-04-18 17:10 UTC, merged